spring.application.name=controlpatrimonial
spring.datasource.url=jdbc:mysql://172.28.3.11:3306/controlpatrimonial?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://localhost:3306/controlpatrimonial
#spring.datasource.username=usercsjar
#spring.datasource.password=$$csjar2024
spring.datasource.username=userncpp
spring.datasource.password=$$ncpp2021
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true

#LLAVE SECRETA
val.secret.key=C0ntrolP@atrimon1al
#VALIDACION TOKEN
val.url.validar=http://localhost:8080/acta/validar
#CLAVE CERTIFICADO
val.certificado.url=D:\\certs\\JORGE FRANKLYN COAQUIRA RAMOS.pfx
#VALIDACION TOKEN
val.certificado.password=100%@dmin

#SERVIDOR FTP
#ftp.server.ip=192.168.1.35
ftp.server.ip=172.28.3.11
ftp.server.puerto=21
ftp.server.usuario=csjar
ftp.server.clave=$$csjar2024

#MICROSERVICIOS
url.servicio.notificacion=http://localhost:8082
servicio.notificacion.enviarEmail=/enviarEmail

url.servicio.personal=http://localhost:8081
servicio.personal.buscarEmpleado=/personal/